name: Testing Calculator
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '18' 
      - name: Create target
        run: mkdir target
      - name: Compile tesing class
        run: javac -d target -cp target: Calculator.java
      - name: Compile test class
        run: javac -d target -cp target: CalculatorTest.java
      - name: Run CalculatorTest.java
        run: java -jar junit-platform-console-standalone-1.7.2.jar --class-path target --select-class CalculatorTest
        #run: java -jar junit-platform-console-standalone-1.6.2.jar